environment: development
server:
  port: 50051
database:
  host: localhost
  port: 5432
  user: auth_user
  password: auth_password
  name: auth_db
redis:
  addr: localhost:6379
kafka:
  broker: localhost:9092
jwt:
  private_key_path: ./certs/private.pem
  public_key_path: ./certs/public.pem